config/routes.rb
Exchange::Application.routes.draw do

  # Root

  root :to => "static_pages#home"

  # Status

  get :status, to: lambda { |_| [200, {}, []] }

  # Gems

  use_doorkeeper do
    skip_controllers :applications
  end

  mount OpenStax::Accounts::Engine, at: "/accounts"
  mount FinePrint::Engine, at: "/fine_print"

  # Administrator

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Agent

  namespace 'manage' do
    get '/', to: 'base#index'

    user_routes :agents

    application_routes :platforms
    application_routes :subscribers
  end

  # Researcher

  namespace 'research' do
    get '/', to: 'base#index'

    resources :events, only: :index
    resources :activities, only: :index
  end

  # JSON API

  apipie

  api :v1, :default => true do
    resources :identifiers, only: :create

    resources :events, only: :index

    scope '/events' do
      scope '/identifiers' do
        event_routes :loads
        event_routes :heartbeats
        event_routes :links
        event_routes :unloads
      end

      scope '/platforms' do
        event_routes :taskings
        event_routes :multiple_choices,
                     to: 'answer_events#create_multiple_choice'
        event_routes :free_responses, to: 'answer_events#create_free_response'
        event_routes :gradings
      end
    end

    resources :activities, only: :index
  end

  # Shared Pages

  # Resources

  resources :terms, only: [:index, :show] do
    scope controller: 'signatures' do
      collection do
        get 'pose', action: :new
        post 'agree', action: :create
      end
    end
  end

  # Singular routes
  # Only for routes with unique names

  scope module: 'static_pages' do
    get 'about'
    get 'copyright'
  end

end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController

  fine_print_skip
  before_filter :can_sign

  layout "layouts/application_body_only"

  def new
    @contracts = params[:terms].collect{|t| FinePrint.get_contract(t)}
  end

  def create
    handle_with(TermsAgree,
                caller: current_account,
                complete: lambda { fine_print_return })
  end

  protected

  def can_sign
    instance_exec current_account, &FinePrint.config.authenticate_user_proc
  end

end

app/views/signatures/new.html.erb
<% signed_before = @contracts.any? do |c|
     FinePrint.signed_any_version_of_contract?(current_account, c)
   end %>

<%= page_heading "Welcome to #{SITE_NAME}" %>

<div class="not-full-width">
  <% if signed_before %>
    <p>There have been changes to the site terms. Please review them and then click "I agree" at the bottom of this page to continue.</p>
  <% else %>
    <p>To activate your account on <%= SITE_NAME %>, please review and accept the following site terms by checking the box below and then clicking "Register".</p>
  <% end %>


  <% contract_links = @contracts.collect do |contract|
    link_to contract.title, term_path(contract), remote: true
  end %>

  <ul class="normal" style="margin-top:20px; margin-bottom: 20px">
    <% contract_links.each do |contract_link| %>
      <li><%= contract_link %></li>
    <% end %>
  </ul>

  <%= lev_form_for :agreement, url: agree_terms_path, method: :post do |f| %>
    <div class="checkbox">
      <label>
        <%= f.check_box :i_agree %> I have read the terms listed above and I agree to be bound by their terms
      </label>
    </div>

    <% @contracts.each do |c| %>
      <%= hidden_field_tag 'agreement[terms][]', c.id %>
    <% end %>

    <%= f.submit (signed_before ? "I Agree" : "Register"), id: "agreement_submit" %>
  <% end %>

  <% content_for :javascript do %>
    <script type="text/javascript">
      Exchange.Ui.enableOnChecked('#agreement_submit', '#agreement_i_agree');
    </script>
  <% end %>

</div>